//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.DanhGia = new HashSet<DanhGia>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public int SoLuongCon { get; set; }
        public double Gia { get; set; }
        public int SoLuong { get; set; }
        public string ThongSoKyThuat { get; set; }
        public string AnhSP { get; set; }
        public Nullable<int> MaHang { get; set; }
        public string MaNhaCungCap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGia { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual PhanLoaiHang PhanLoaiHang { get; set; }
       
    }
}
